# Access to Healthy Assets and Hazards
a scoring methodology that ranks access for LSOAS
similar to the Indicies of Deprivation

data can be accessed and downloaded [here](https://data.geods.ac.uk/dataset/access-to-healthy-assets-hazards-ahah)

online maps can be played with [here](https://mapmaker.geods.ac.uk/#/access-healthy-assets-hazards)

you will need to create an account

download the csv save it alongside this notebook

In [ ]:
import polars as pl
import polars.selectors as cs
import plotly.express as px

from jsna_climate_and_environment.indicies_of_deprivation.iod25 import get_imd_domains, get_underlying_indicators
from jsna_climate_and_environment.geography.places import read_gdb
from jsna_climate_and_environment.config import DATA_DIR

2026-03-26 15:11:46.619 | INFO     | jsna_climate_and_environment.config:<module>:23 - ROOT_DIR: D:\nmolkent\code\jsna-climate-and-environment

In [5]:
link_df = pl.from_pandas(read_gdb("linking"))
link_df

shape: (719, 8)
┌────────────┬────────────┬────────────┬──────────┬────────────┬───────────┬───────────┬───────────┐
│ country_co ┆ region_cod ┆ county_cod ┆ lgr_code ┆ district_c ┆ msoa21_co ┆ lsoa21_co ┆ source_ur │
│ de         ┆ e          ┆ e          ┆ ---      ┆ ode        ┆ de        ┆ de        ┆ l         │
│ ---        ┆ ---        ┆ ---        ┆ str      ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ str        ┆ str        ┆          ┆ str        ┆ str       ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪══════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000209  ┆ E02006349 ┆ E01030488 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000213  ┆ E02006404 ┆ E01030711 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000209  ┆ E02006349 ┆ E01030485 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000217  ┆ E02006461 ┆ E01030990 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000216  ┆ E02006455 ┆ E01030926 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ …          ┆ …          ┆ …          ┆ …        ┆ …          ┆ …         ┆ …         ┆ …         │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000217  ┆ E02006467 ┆ E01030944 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000209  ┆ E02006360 ┆ E01030472 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000216  ┆ E02006440 ┆ E01030891 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_EAST ┆ E07000210  ┆ E02006371 ┆ E01030536 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
│ E92000001  ┆ E12000008  ┆ E10000030  ┆ SCC_WEST ┆ E07000212  ┆ E02006399 ┆ E01030651 ┆ https://h │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ ub.arcgis │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ .com/api/ │
│            ┆            ┆            ┆          ┆            ┆           ┆           ┆ v3/…      │
└────────────┴────────────┴────────────┴──────────┴────────────┴───────────┴───────────┴───────────┘

In [4]:
lsoa_gdf = read_gdb("lsoa")
lsoa_gdf

,lsoa21_code,lsoa21_name,source_url,geometry
0,E01030296,Elmbridge 015A,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((517080.666 164767.597, 517080...."
1,E01030297,Elmbridge 015B,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((515036 164690.752, 515038.813 ..."
2,E01030298,Elmbridge 015C,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((516150.144 164498.2, 516200.87..."
3,E01030299,Elmbridge 015D,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((515282.144 163601.63, 515307.6..."
4,E01030300,Elmbridge 017A,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((511271.573 160957.78, 511265.0..."
...,...,...,...,...
716,E01035360,Reigate and Banstead 016G,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((527848.04 144674.199, 527859 1..."
717,E01035361,Reigate and Banstead 018F,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((528530.714 143218.357, 528543...."
718,E01035362,Reigate and Banstead 018G,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((528763 143199.817, 528761.044 ..."
719,E01035363,Tandridge 002E,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((533975.062 158553, 533976.895 ..."
720,E01035364,Tandridge 002F,https://services1.arcgis.com/ESMARspQHYMw9BZ9/...,"MULTIPOLYGON (((534472 158635.821, 534465.159 ..."

In [6]:
imd = pl.concat([
    get_underlying_indicators().join(link_df.select("district_code", lsoa21cd="lsoa21_code", ), on="lsoa21cd"),
    get_imd_domains().join(link_df.select("district_code", lsoa21cd="lsoa21_code", ), on="lsoa21cd"),
], how="vertical_relaxed")
imd

shape: (38_826, 8)
┌───────────┬───────────────┬────────────┬──────────────┬────────┬─────────┬────────┬──────────────┐
│ lsoa21cd  ┆ population_es ┆ domain     ┆ indicator    ┆ score  ┆ rank    ┆ decile ┆ district_cod │
│ ---       ┆ timate_2022   ┆ ---        ┆ ---          ┆ ---    ┆ ---     ┆ ---    ┆ e            │
│ str       ┆ ---           ┆ str        ┆ str          ┆ f64    ┆ f64     ┆ f64    ┆ ---          │
│           ┆ i64           ┆            ┆              ┆        ┆         ┆        ┆ str          │
╞═══════════╪═══════════════╪════════════╪══════════════╪════════╪═════════╪════════╪══════════════╡
│ E01030296 ┆ null          ┆ income     ┆ income_domai ┆ 25.0   ┆ null    ┆ null   ┆ E07000207    │
│           ┆               ┆            ┆ n_numerator  ┆        ┆         ┆        ┆              │
│ E01030297 ┆ null          ┆ income     ┆ income_domai ┆ 115.0  ┆ null    ┆ null   ┆ E07000207    │
│           ┆               ┆            ┆ n_numerator  ┆        ┆         ┆        ┆              │
│ E01030298 ┆ null          ┆ income     ┆ income_domai ┆ 290.0  ┆ null    ┆ null   ┆ E07000207    │
│           ┆               ┆            ┆ n_numerator  ┆        ┆         ┆        ┆              │
│ E01030299 ┆ null          ┆ income     ┆ income_domai ┆ 165.0  ┆ null    ┆ null   ┆ E07000207    │
│           ┆               ┆            ┆ n_numerator  ┆        ┆         ┆        ┆              │
│ E01030300 ┆ null          ┆ income     ┆ income_domai ┆ 415.0  ┆ null    ┆ null   ┆ E07000207    │
│           ┆               ┆            ┆ n_numerator  ┆        ┆         ┆        ┆              │
│ …         ┆ …             ┆ …          ┆ …            ┆ …      ┆ …       ┆ …      ┆ …            │
│ E01035360 ┆ 2061          ┆ living_env ┆ outdoors_sub ┆ -0.368 ┆ 22486.0 ┆ 7.0    ┆ E07000211    │
│           ┆               ┆            ┆ _domain      ┆        ┆         ┆        ┆              │
│ E01035361 ┆ 1443          ┆ living_env ┆ outdoors_sub ┆ 0.472  ┆ 8229.0  ┆ 3.0    ┆ E07000211    │
│           ┆               ┆            ┆ _domain      ┆        ┆         ┆        ┆              │
│ E01035362 ┆ 1306          ┆ living_env ┆ outdoors_sub ┆ 0.747  ┆ 5309.0  ┆ 2.0    ┆ E07000211    │
│           ┆               ┆            ┆ _domain      ┆        ┆         ┆        ┆              │
│ E01035363 ┆ 1435          ┆ living_env ┆ outdoors_sub ┆ 0.803  ┆ 4817.0  ┆ 2.0    ┆ E07000215    │
│           ┆               ┆            ┆ _domain      ┆        ┆         ┆        ┆              │
│ E01035364 ┆ 1215          ┆ living_env ┆ outdoors_sub ┆ 0.78   ┆ 5012.0  ┆ 2.0    ┆ E07000215    │
│           ┆               ┆            ┆ _domain      ┆        ┆         ┆        ┆              │
└───────────┴───────────────┴────────────┴──────────────┴────────┴─────────┴────────┴──────────────┘

In [ ]:
from jsna_climate_and_environment.config import DATA_DIR
aha = pl.read_csv(DATA_DIR / "raw" / "ahah_v5.csv").rename(str.lower)    
index_type = pl.col("variable").str.extract(r"rnk\z|pct\z", 0).fill_null("score").replace({"rnk": "rank", "pct": "percentile"})
domain_map = {
    "gp": "health",	
    "bluespace": "greenspace_bluespace",
    "dentist": "health",
    "fast_food": "retail",
    "gambling": "retail",
    "greenspace_active": "greenspace_bluespace",
    "hospital": "health",
    "leisure": "health",
    "pharmacy": "health",
    "pub_bar": "retail",
    "tobacco": "retail",
    "no2": "air_quality",
    "pm10": "air_quality",
    "so2": "air_quality",
    "greenspace": "greenspace_bluespace",
    "ahah": "overall_index",
    "domain_h": "health",
    "domain_g": "greenspace_bluespace",
    "domain_e": "air_quality",
    "domain_r": "retail",
}

ranking_system = "lower (better) rank = lower (better) decile"
travel_time_ranking = f"scored by travel time - lower travel time = better access = {ranking_system}"
shortest_distance_ranking = f"scored by distance - shorter distance = better access = {ranking_system}"
longest_distance_ranking = f"scored by distance - longer distance = healthier = {ranking_system}"
ndvi_ranking = f"scored by NDVI - higher NDVI = more vegetation = {ranking_system}"
polution_ranking = f"scored by concentration of polutant in air - lower pollution = healthier = {ranking_system}"
aggregation_ranking = f"scored by aggregation - lower (better) score = {ranking_system}"

score_description_map = {
    "gp": travel_time_ranking,	
    "bluespace": shortest_distance_ranking,
    "dentist": travel_time_ranking,
    "fast_food": longest_distance_ranking,
    "gambling": longest_distance_ranking,
    "greenspace_active": shortest_distance_ranking,
    "hospital": shortest_distance_ranking,
    "leisure": shortest_distance_ranking,
    "pharmacy": shortest_distance_ranking,
    "pub_bar": longest_distance_ranking,
    "tobacco": longest_distance_ranking,
    "no2": polution_ranking,
    "pm10": polution_ranking,
    "so2": polution_ranking,
    "greenspace": ndvi_ranking,
    "ahah": aggregation_ranking,
    "domain_h": aggregation_ranking,
    "domain_g": aggregation_ranking,
    "domain_e": aggregation_ranking,
    "domain_r": aggregation_ranking,
}


pivoted = (
    aha
    .unpivot(
        index=[
            "lsoa21cd",
        ],
    )
    .with_columns(
        index_type=index_type, 
        indicator=pl.col("variable").str.replace(r"_rnk\z|_pct\z", "").str.strip_prefix("vape_")
    )
    .pivot(
        "index_type",
        values="value",
        index=[
            "lsoa21cd",
            "indicator",
        ],
    )
    .with_columns(
        domain=pl.col("indicator").replace_strict(domain_map),
        decile=(pl.col("percentile") % 10).cast(pl.Int32) + 1,
        description=pl.col("indicator").replace_strict(score_description_map)
    )
)
pivoted

shape: (861_280, 8)
┌───────────┬───────────┬───────────┬─────────┬────────────┬───────────────┬────────┬──────────────┐
│ lsoa21cd  ┆ indicator ┆ score     ┆ rank    ┆ percentile ┆ domain        ┆ decile ┆ description  │
│ ---       ┆ ---       ┆ ---       ┆ ---     ┆ ---        ┆ ---           ┆ ---    ┆ ---          │
│ str       ┆ str       ┆ f64       ┆ f64     ┆ f64        ┆ str           ┆ i32    ┆ str          │
╞═══════════╪═══════════╪═══════════╪═════════╪════════════╪═══════════════╪════════╪══════════════╡
│ E01000001 ┆ gp        ┆ 1.886601  ┆ 20221.0 ┆ 46.0       ┆ health        ┆ 7      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ travel time  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ E01000002 ┆ gp        ┆ 1.85      ┆ 19657.0 ┆ 45.0       ┆ health        ┆ 6      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ travel time  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ E01000003 ┆ gp        ┆ 2.25      ┆ 25282.0 ┆ 58.0       ┆ health        ┆ 9      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ travel time  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ E01000005 ┆ gp        ┆ 2.218924  ┆ 24918.0 ┆ 57.0       ┆ health        ┆ 8      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ travel time  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ E01000006 ┆ gp        ┆ 0.714286  ┆ 1079.0  ┆ 2.0        ┆ health        ┆ 3      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ travel time  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ …         ┆ …         ┆ …         ┆ …       ┆ …          ┆ …             ┆ …      ┆ …            │
│ W01002036 ┆ ahah      ┆ 18.069026 ┆ 17650.0 ┆ 41.0       ┆ overall_index ┆ 2      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ aggregation  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ W01002037 ┆ ahah      ┆ 22.269307 ┆ 26154.0 ┆ 61.0       ┆ overall_index ┆ 2      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ aggregation  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ W01002038 ┆ ahah      ┆ 18.859831 ┆ 19367.0 ┆ 45.0       ┆ overall_index ┆ 6      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ aggregation  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ W01002039 ┆ ahah      ┆ 15.928863 ┆ 12775.0 ┆ 30.0       ┆ overall_index ┆ 1      ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ aggregation  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
│ W01002040 ┆ ahah      ┆ 21.805694 ┆ 25331.0 ┆ 59.0       ┆ overall_index ┆ 10     ┆ scored by    │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ aggregation  │
│           ┆           ┆           ┆         ┆            ┆               ┆        ┆ - lower …    │
└───────────┴───────────┴───────────┴─────────┴────────────┴───────────────┴────────┴──────────────┘

In [11]:
from pathlib import Path
output_path = Path("D:/nmolkent/data/climate")
output_path.mkdir(exist_ok=True, parents=True)

pivoted.filter(pl.col("lsoa21cd").is_in(link_df["lsoa21_code"].to_list())).write_csv(output_path / "ahah.csv")
imd.filter(pl.col("lsoa21cd").is_in(link_df["lsoa21_code"].to_list())).write_csv(output_path / "iod.csv")

In [ ]:
pivoted.pivot(on="indicator", index="lsoa21cd", values="percentile").join(district_lookup, on="lsoa21cd")

shape: (43_064, 21)
┌───────────┬──────┬───────────┬─────────┬───┬──────────┬──────────┬──────────┬───────┐
│ lsoa21cd  ┆ gp   ┆ bluespace ┆ dentist ┆ … ┆ domain_g ┆ domain_e ┆ domain_r ┆ ahah  │
│ ---       ┆ ---  ┆ ---       ┆ ---     ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---   │
│ str       ┆ f64  ┆ f64       ┆ f64     ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64   │
╞═══════════╪══════╪═══════════╪═════════╪═══╪══════════╪══════════╪══════════╪═══════╡
│ E01000001 ┆ 46.0 ┆ 96.0      ┆ 15.0    ┆ … ┆ 100.0    ┆ 100.0    ┆ 86.0     ┆ 100.0 │
│ E01000002 ┆ 45.0 ┆ 97.0      ┆ 2.0     ┆ … ┆ 100.0    ┆ 100.0    ┆ 88.0     ┆ 100.0 │
│ E01000003 ┆ 58.0 ┆ 98.0      ┆ 10.0    ┆ … ┆ 99.0     ┆ 100.0    ┆ 86.0     ┆ 100.0 │
│ E01000005 ┆ 57.0 ┆ 74.0      ┆ 27.0    ┆ … ┆ 99.0     ┆ 100.0    ┆ 98.0     ┆ 100.0 │
│ E01000006 ┆ 2.0  ┆ 85.0      ┆ 54.0    ┆ … ┆ 99.0     ┆ 98.0     ┆ 71.0     ┆ 99.0  │
│ …         ┆ …    ┆ …         ┆ …       ┆ … ┆ …        ┆ …        ┆ …        ┆ …     │
│ W01002036 ┆ 68.0 ┆ 48.0      ┆ 72.0    ┆ … ┆ 61.0     ┆ 42.0     ┆ 42.0     ┆ 41.0  │
│ W01002037 ┆ 55.0 ┆ 17.0      ┆ 76.0    ┆ … ┆ 82.0     ┆ 41.0     ┆ 35.0     ┆ 61.0  │
│ W01002038 ┆ 98.0 ┆ 49.0      ┆ 31.0    ┆ … ┆ 71.0     ┆ 18.0     ┆ 5.0      ┆ 45.0  │
│ W01002039 ┆ 99.0 ┆ 29.0      ┆ 57.0    ┆ … ┆ 19.0     ┆ 15.0     ┆ 4.0      ┆ 30.0  │
│ W01002040 ┆ 59.0 ┆ 11.0      ┆ 63.0    ┆ … ┆ 83.0     ┆ 33.0     ┆ 25.0     ┆ 59.0  │
└───────────┴──────┴───────────┴─────────┴───┴──────────┴──────────┴──────────┴───────┘

In [ ]:
px.scatter_matrix(
    pivoted.pivot(on="indicator", index="lsoa21cd", values="score").join(district_lookup, on="lsoa21cd"),
    color="district",
    hover_data="lsoa21cd",
    dimensions=pivoted.filter(domain=pl.lit("greenspace_bluespace"))["indicator"].unique()
)

In [ ]:
px.scatter(
    aha.select("lsoa21cd", pl.col("district").fill_null(pl.lit("elsewhere")), air_quality="domain_e", green_or_bluespace="domain_g", health="domain_h", retail="domain_r"), 
    y="health", x="retail",
    color="district",
    height=500,
    width=700,
)

In [ ]:
px.scatter(
    aha.select("lsoa21cd", pl.col("district").fill_null(pl.lit("elsewhere")), air_quality="domain_e", green_or_bluespace="domain_g", health="domain_h", retail="domain_r"), 
    y="health", x="air_quality",
    color="district",
    height=500,
    width=700,
)

In [ ]:
px.scatter(
    aha.select("lsoa21cd", pl.col("district").fill_null(pl.lit("elsewhere")), air_quality="domain_e", green_or_bluespace="domain_g", health="domain_h", retail="domain_r"), 
    y="health", x="green_or_bluespace",
    color="district",
    height=500,
    width=700,
)